### ISSUE TITLE
Issue running

### ISSUE THREAD

**Issue by DankMemeGuy** [Pikurrot/whisper-gui#26]
```
Checking conda installation...
conda is installed.
Checking config file...
Activating environment whisperx...
Environment activated.
Checking for updates...
Failed to fetch updates. Check your internet connection.
Running Whisper-GUI...
Creating interface...
Traceback (most recent call last):
  File "C:\Users\Aiden\Downloads\whisper-gui-2.3.0\main.py", line 433, in <module>
    demo.launch(inbrowser=args.autolaunch, share=args.share)
  File "C:\Users\Aiden\anaconda3\envs\whisperx\lib\site-packages\gradio\blocks.py", line 2327, in launch
    ) = http_server.start_server(
  File "C:\Users\Aiden\anaconda3\envs\whisperx\lib\site-packages\gradio\http_server.py", line 154, in start_server
    raise OSError(
OSError: Cannot find empty port in range: 7860-7959. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`.
Press any key to continue . . .
```

any ideas? I tried adding port 7860 to my firewall and that didn't change anything

**Comment by Pikurrot** [comment]
Similar issue here: https://github.com/CompVis/stable-diffusion/issues/424
They propose different solutions, mostly for Windows. I don't know your environment so try any of those and see if they work.
Let me know if you solve it.
